### ISSUE TITLE
Watcher Option

### ISSUE THREAD

**Issue by ghost** [christian-reichart/svg-chameleon#24]
This is more a discussion, than a feature request.
Would it make sense to have a --watch option in the CLI, so that the Sprite and CSS automatically get recreated if the source SVGs change?

**Comment by christian-reichart** [comment]
@joachim-pryntad I don't see a huge benefit in this, since icons in a project don't change _too_ often. To replace the manual task of running the script you can also integrate it in your pipeline, so at least for deployments it can't be forgotten.

**Comment by christian-reichart** [comment]
Also npm-watch can be used for this
