### ISSUE TITLE
Not working on Apple M1

### ISSUE THREAD

**Issue by ddanier** [christian-reichart/svg-chameleon#25]
As svg-chameleon depends on svg-sprite which itself depends on a phantomjs-prebuilt - a project being dead for years and not providing any ARM64 builds....

svg-chameleon cannot be used on Apple M1 currently :(

**Comment by ddanier** [comment]
Also see:
* https://github.com/svg-sprite/svg-sprite/issues/254
* https://github.com/svg-sprite/svg-sprite/pull/447

**Comment by christian-reichart** [comment]
@ddanier Thanks! This is linked to https://github.com/christian-reichart/svg-chameleon/issues/5 , will look into this soon.

**Comment by ddanier** [comment]
Note: It seems to work on MacOS directly when rosetta is installed...but not inside docker. See thread in svg-sprite ticket. :)

**Comment by ddanier** [comment]
I might have found a workaround:

```
FROM node:lts

# Install phantomjs globally, so we can skip phantomjs-prebuilt
RUN apt-get update && \
    apt-get install -y phantomjs && \
    rm -rf /var/lib/apt/lists/*

ENV DISPLAY=:0
ENV QT_QPA_PLATFORM='offscreen'
```

Meaning create your own docker image and install the phantomjs package the distribution provides. phantomjs-prebuild will then not try to fetch the binaries again. The ENV in necessary for phantomjs to work as it tries to use the X server by default.

**Comment by christian-reichart** [comment]
@ddanier seems like with v2.0.0 we will finally be able to ditch PhantomJS. Will keep an eye out for the stable release.
https://github.com/svg-sprite/svg-sprite/issues/446

**Comment by ddanier** [comment]
@christian-reichart Great news :)

**Comment by ddanier** [comment]
@christian-reichart Any news on switching to svg-sprite v2?

**Comment by christian-reichart** [comment]
@ddanier  I've just pushed changes to master, updating the versions of svg-sprite and svgo.

However I'm currently having problems publishing the version on npm, since my old email doesn't exist anymore and I can't login. :D Hope this will be resolved in the next days.

Feel free to install it directly from GitHub though and let me know if everything works. I've done some testing, but this tool still lacks a decent testing setup to be 100% sure... :D

**Comment by ademeter** [comment]
@christian-reichart 

Hi Chris,
looks good to me. :) The generated sprite differs from the old sprite when checking the changes in the code, but with no visible impact on the user interface.

I am looking forward to the new version on npm.

**Comment by christian-reichart** [comment]
Hi @ademeter  @ddanier ,
thanks for testing it! v1.0.0 has been released on npm, removing the dependency on PhantomJS

**Comment by christian-reichart** [comment]
@ademeter Can you by any chance send me the two sprites you have generated? If they can't be shared publicly, you can send them to me via mail [hello@christianreich.art](mailto:hello@christianreich.art).

I'm curious to see what exactly changed and if I see any problems that maybe don't occur in your usage.

**Comment by ddanier** [comment]
@christian-reichart Thank you so much! 👍

**Comment by christian-reichart** [comment]
@ademeter  @ddanier  just found out that version 1.0.0 wasn't working for me because of old svgo types. If you ever run into the issue that the script doesn't do anything, try upgrading to 1.0.1, that should fix it.
