### ISSUE TITLE
Use .json File for config

### ISSUE THREAD

**Issue by TheJotob** [christian-reichart/svg-chameleon#6]
For CI or Taskrunner it would be nice to have one js / json file, where you can put all the configuration.

Like you have a webpack.config.js it would be nice to have a chameleon.config.js(on) to be able to put all the configuration in one place. Otherwise predefined cli commands i.e. in the package.json might get very long and hard to read / maintain.

**Comment by christian-reichart** [comment]
Resolved in #8
