### ISSUE TITLE
Add option to define complete output path

### ISSUE THREAD

**Issue by TheJotob** [christian-reichart/svg-chameleon#7]
If you have a strict separation between Source files and Files to be served to the user you might not want to have the compiled sprite in a subfolder but in a completely separate public folder.

I work a lot with TYPO3 and there we usually have our Source images in a Folder .../Resources/Private/Icons/ and the resulting sprite would need to go to .../Resources/Public/Icons/ so this would be nice to be possible.

And while someone (TM) is on the topic of adding configurable paths it would be awesome if the SCSS could be rendered into a different path than the Sprite. (In my TYPO3 example the scss would be rendered into .../Resources/Private/Scss/.../sprite.scss)

**Comment by christian-reichart** [comment]
We could rework the options as follows I think:

``` javascript
let opts = {
  path: null, // default is cwd
  dest: null,  // default is path + name as subfolder, if dest is specified no additional subfolder is created (must be included in string)
  // remove subdirName option
  name: 'chameleon-sprite',
  dimensionStyles: {
    css: {
      create: false, // automatically true if other option is set
      dest: null, // default same dir as sprite
      name: null // default is name
    },
    scss: {
      create: false, // automatically true if other option is set
      dest: null, // default same dir as sprite
      name: null // default is name
    },
  },
};
```

command line options have to be reworked as well for this

**Comment by TheJotob** [comment]
Looks good for me :)
But I think this is blocked by #6 right now because there is a lot happening with how the configuration work. I guess we should wait with the implementation of this issue until the other one is completed

**Comment by harterSe** [comment]
@christian-reichart, @TheJotob  Can i take this issue or is someone already working on it.

**Comment by christian-reichart** [comment]
@harterSe Would like to have typing in master before we continue changing the code base too much #1

**Comment by christian-reichart** [comment]
@harterSe  sorry for the long wait. Typing is now merged to master, are you still interested in tackling this issue?

**Comment by harterSe** [comment]
@christian-reichart I'm sill interested in solving this issue. I will take a look today.

**Comment by TheJotob** [comment]
@christian-reichart  @harterSe this feature works perfectly now. We where able to integrate SVG Chameleon into our TYPO3 project without a problem. Thank you both :)
I think this issue can be closed now
